version: '3'
services:
  db:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
